automation_server/app/models/trip.py
import datetime
import copy

# import db from app
from app import db

from . import exceptions
from docx import Document


class Ticket(db.Model):
    __tablename__ = 'tickets'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    date = db.Column(db.Date, nullable=False)
    bought = db.Column(db.Boolean, nullable=False)
    price = db.Column(db.Float, nullable=True)
    trip_id = db.Column(db.Integer, db.ForeignKey('trips.id'), nullable=False)

    def __init__(self,name: str,date:str):
        self.name = name
        self.date = datetime.datetime.strptime(date,"%d %b %y")
        self.bought = False

class Trip(db.Model):
    __tablename__ = 'trips'

    id = db.Column(db.Integer, primary_key=True)
    guest_name = db.Column(db.String(100),nullable=False)
    start_date = db.Column(db.Date,nullable=False)
    end_date = db.Column(db.Date,nullable=False)
    adults = db.Column(db.Integer,nullable=False)
    children = db.Column(db.Integer,nullable=False)
    children_below_six = db.Column(db.Integer,nullable=False)
    attraction_tickets = db.relationship('Ticket', backref='trip', lazy=True, cascade='all, delete-orphan')
    whatsapp_group_id = db.Column(db.String(100),nullable=True)

    def __init__(self):
        self.guest_name = ""
        self.adults = 0
        self.children = 0
        self.children_below_six = 0
        self.attraction_tickets = []
    
    def populate_manually(self, guest_name, adults, children, children_below_six,attraction_tickets,start_date,end_date):
        self.guest_name = guest_name
        self.adults = adults
        self.children = children
        self.children_below_six = children_below_six
        self.start_date = start_date
        self.end_date = end_date

        for ticket in attraction_tickets:
            self.attraction_tickets.append(Ticket(ticket.name,ticket.date))

    def populate_with_docx(self,file_path):
        try:
            document = Document(file_path)
        except:
            raise exceptions.Document("there is an error opening the document")
        
        parsing_guest = False
        parsing_ticket = False
        parsing_dates = False

        for paragraph in document.paragraphs:
            if paragraph.text.startswith("Guest name"):
                guest = paragraph.text.split("\t")[1].split(" X ")
                self.guest_name = ' '.join(guest[0].split(" ")[1:]) # to remove the mr. or ms.
                guest_num = guest[1] # get the guest num from guest name
                parsing_guest = True
                continue

            if paragraph.text.startswith("Flight"):
                parsing_dates = True
                continue

            if parsing_guest:
                if paragraph.text.__contains__("+"):
                    guest_num += paragraph.text.strip("\t")
                else:
                    parsing_guest = False
            
            if parsing_dates:
                if paragraph.text == "":
                    parsing_dates = False
                    continue
                
                date = paragraph.text.split(" ")
                if date[2] == "ARR":
                    self.start_date = datetime.datetime.strptime(' '.join(date[:2] + [datetime.date.today().strftime("%y")]),"%d %b %y")
                    if self.start_date < datetime.datetime.now():
                        self.start_date = datetime.date(self.start_date.year + 1, self.start_date.month, self.start_date.day)
                if date[2] == "DEP":
                    self.end_date = datetime.datetime.strptime(' '.join(date[:2] + [datetime.date.today().strftime("%y")]),"%d %b %y")
                    if self.end_date < datetime.datetime.now():
                        self.end_date = datetime.date(self.end_date.year + 1, self.end_date.month, self.end_date.day)
                    
            if paragraph.text.startswith("Tickets"):
                guest_num_ticket = paragraph.text.split(" for ")[1] # get the guest num from tickets header
                parsing_ticket = True
                continue

            if parsing_ticket:
                if paragraph.text == "":
                    parsing_ticket = False
                    continue
                date, tickets_for_the_date = paragraph.text.strip(".").split(":")
                tickets_for_the_date = tickets_for_the_date.strip().split(", ")
                for item in tickets_for_the_date:
                    self.attraction_tickets.append(Ticket(item,date))
        
        if guest_num != guest_num_ticket:
            raise exceptions.Mismatch("there is a mismatch in the number of guest")

        guests = guest_num.split("+")
        for category in guests:
            if category.__contains__("adults"):
                self.adults = int(category.split(" ")[0])
            
            if category.__contains__("child"):
                self.children = int(category.strip().split(" ")[0])
                children_age_str = category.strip().split("(")[-1].strip("years)").split(" / ")
                children_age = list(map(lambda x: int(x.strip()), children_age_str))

                for age in children_age:
                    if age <= 6:
                        self.children_below_six += 1
    
    def add_whatsapp_group_id(self,group_id:str):
        self.whatsapp_group_id = group_id

    def tickets_to_buy(self):
        tickets_to_buy = copy.deepcopy(self.attraction_tickets)
        

automation_server/app/routes.py
import os
import sys
import time
from random import randint

from pathlib import Path
from dotenv import load_dotenv

from werkzeug.utils import secure_filename
from flask import Blueprint, request, request, redirect, url_for, render_template, current_app
from sqlalchemy import func

from datetime import date, datetime
from .models.trip import Trip, Ticket
from .utils.transfer_message import Customer_Tranfer, get_customer_transfers
from .utils.whatsapp_service import get_whatsapp_service
from . import db 

bp = Blueprint('routes', __name__)

upload_bp = Blueprint('upload', __name__, template_folder='../templates')

def get_exe_dir():
    if getattr(sys, 'frozen', False):
        # If running from a PyInstaller bundle
        return Path(sys.executable).parent
    else:
        # If running from source
        return Path(__file__).resolve().parent.parent


env_path = get_exe_dir() / ".env"
load_dotenv(dotenv_path=env_path)

source_folder = os.getenv("SOURCE_FOLDER")
transporter_group_id = os.getenv("TRANSPORTER_CHAT_GROUP_ID")

@bp.route('/')
def index():
    upcoming_trips = Trip.query.filter(
        func.date(Trip.start_date) > func.date(date.today())).all()
    ongoing_trips = Trip.query.filter(
        func.date(Trip.end_date) >= func.date(date.today()),
        func.date(Trip.start_date) <= func.date(date.today())
        ).all()
    
    return render_template('index.html', ongoing_trips=ongoing_trips, upcoming_trips=upcoming_trips)


@bp.route('/past-trips')
def past_trips():
    past_trips = Trip.query.filter(
        func.date(Trip.end_date) < func.date(date.today())).all()
    return render_template('past_trips.html', past_trips=past_trips)

@bp.route('/add-docx',methods=['POST'])
def add_trip_with_docx():
    uploaded_file = request.files.get('input_file')
    if not uploaded_file:
        return "No file uploaded", 400

    filename = secure_filename(uploaded_file.filename)
    upload_folder = current_app.config['VOUCHER']
    file_path = os.path.join(upload_folder, filename)
    uploaded_file.save(file_path)

    # Add file
    new_trip = Trip()
    new_trip.populate_with_docx(file_path)
    same_trip = Trip.query.filter(
        func.lower(Trip.guest_name) == func.lower(new_trip.guest_name),
        func.date(Trip.start_date) == func.date(new_trip.start_date), 
        func.date(Trip.end_date) == func.date(new_trip.end_date)).all()
    if len(same_trip) == 0:    
        db.session.add(new_trip)
        db.session.commit()
        return "Trip added!", 201
    else: 
        return "Trip exists!", 200

@bp.route('/add-manually', methods=['GET', 'POST'])
def add_trip_manually():
    if request.method == 'POST':
        # User submits trip manually
        start_date = datetime.strptime(request.form['start_date'][:10],'%Y-%m-%d')
        end_date = datetime.strptime(request.form['end_date'][:10],'%Y-%m-%d')
        
        new_trip = Trip()

        new_trip.populate_manually(request.form['guest_name'],request.form['adults'],request.form['children'],request.form['children_below_six'],[],start_date,end_date)
        db.session.add(new_trip)
        db.session.commit()
        return redirect(url_for('routes.trip',trip_id=new_trip.id))
    return render_template("add_trip.html")

@bp.route('/add-ticket/<int:trip_id>',methods=['POST'])
def add_ticket(trip_id):
    trip = Trip.query.get_or_404(trip_id)
    if not trip:
        return "Trip not found"
    
    uploaded_file = request.files.getlist('input_file')

    if not uploaded_file:
        return "No file uploaded", 400
    
    for file in uploaded_file:
        filepath = file.filename  # This includes the folder path from client
        newfilepath = trip.guest_name + '/' + '/'.join(filepath.split("/")[1:]) # add tickets with root file name as guest_name accoridng to trip id
        upload_folder = current_app.config['TICKET']
        file_path = os.path.join(upload_folder, newfilepath)
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        file.save(file_path)

    return 'Folder uploaded successfully!'

@bp.route('/delete-trip/<int:trip_id>', methods=['POST'])
def delete_trip(trip_id):
    trip = Trip.query.get_or_404(trip_id)
    db.session.delete(trip)
    db.session.commit()
    return "success"

@bp.route('/whatsapp_group_id/<int:trip_id>', methods=['GET', 'POST'])
def whatsapp_group_id(trip_id):
    # Fetch the trip by ID
    trip = Trip.query.get_or_404(trip_id)
    
    # Check if today's date is greater than or equal to the end_date
    if request.method == 'POST':
        # User submits feedback
        trip.whatsapp_group_id = request.form['group_id']
        db.session.commit()
        return redirect(url_for('routes.trip', trip_id=trip.id))
    
    # If it's the correct time, render a form for the user to fill in feedback
    return render_template('request_whatsapp_group_id.html', trip=trip)

@bp.route('/trip/<int:trip_id>', methods=['GET', 'POST'])
def trip(trip_id):
    trip = Trip.query.get_or_404(trip_id)
    return render_template('trip.html', trip=trip)

@bp.route('/send-trip-sheet')
def send_trip_sheet():
    try:
        whatsapp = get_whatsapp_service()
        
        target_file_name = "ody" + datetime.strftime(datetime.now(),"%Y%m%d") + ".xlsx"
        destination_folder = os.path.join(os.getcwd(), "trip_sheet/transporter")

        isSuccess = whatsapp.go_to_chat(transporter_group_id)
        if not isSuccess:
            return "Cannot find chat"
        hasTodayTripSheet = whatsapp.find_file(target_file_name,source_folder,destination_folder)
        if not hasTodayTripSheet:
            return "No trip sheet for today"
        
        file_path = os.path.join(destination_folder,target_file_name)
        # get customer transfers from transporter trip sheet
        customer_transfers = get_customer_transfers(file_path)

        if not customer_transfers:
            return "failed"
        errors = {}
        for customer in customer_transfers:
            trip = Trip.query.filter(
            func.lower(Trip.guest_name) == func.lower(customer.guest_name),
            func.date(Trip.start_date) <= func.date(customer.date),
            func.date(Trip.end_date) >= func.date(customer.date)).all()
            if not trip:
                errors["missing_trip"] = errors.get("missing_trip",[]) + [customer.guest_name]
            elif not trip[0].whatsapp_group_id:
                errors["missing_whatsapp_group_id"] = errors.get("missing_whatsapp_group_id",[]) + [customer.guest_name]
            else:
                goToChat = whatsapp.go_to_chat(trip[0].whatsapp_group_id)
                sentMessage = whatsapp.send_message(customer.output_message())
                if not goToChat or not sentMessage:
                    errors["error_sending_message"] = errors.get("sending_message",[]) + [customer.guest_name]

            
            # Send tickets
            # Find the tickets for the day
            ticket_folder = current_app.config['TICKET']
            path1 = os.path.join(ticket_folder, customer.guest_name)
            path2 = os.path.join(path1, datetime.strftime(customer.date,"%d %b %Y"))

            if not os.path.isdir(path1):
                # if no ticket file
                continue
            
            if not os.path.isdir(path2):
                # if not ticket for today
                continue
            
            # Get all files (not directories) inside the second folder
            files = [f for f in os.listdir(path2) if os.path.isfile(os.path.join(path2, f))]
            for filename in files:
                filepath = os.path.join(path2,filename)
                sentTickets = whatsapp.send_document(filepath)
                time.sleep(randint(3,6))
                if not sentTickets:
                    errors["error_sending_ticket"] = errors.get("sending_message",[]) + [filename]
                
        if len(errors) != 0:
            out = []
            for error, customer_name in errors.items():
                out.append(f'<p>{error}: {customer_name}</p>')
            return ''.join(out)
        
        return "success"
    except Exception as e:
        print(e)
        return "An error occurred"

@bp.route('/whatsapp/login')
def whatsapp_login():
    try:
        whatsapp = get_whatsapp_service()
        return "Successfully logged in to whatsapp"
    except:
        return "an error occurred"

automation_server/app/templates/add_trip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style.css">
    <title>Add Trip Manually</title>
</head>
<body>
    <h1>Add Trip Manually</h1>
    <form method="POST">
        <label for="guest_name">Guest Name</label>
        <input type="text" name="guest_name" rows="1" cols="50"></input>
        <br>
        <label for="adults">Adults</label>
        <input type="text" name="adults" rows="1" cols="50"></input>
        <br>
        <label for="children">Children</label>
        <input type="text" name="children" rows="1" cols="50"></input>
        <br>
        <label for="children_below_six">Children Below Six</label>
        <input type="text" name="children_below_six" rows="1" cols="50"></input>
        <br>
        <label for="start_date">Start Date</label>
        <input type="date" name="start_date" rows="1" cols="50"></input>
        <br>
        <label for="end_date">End Date</label>
        <input type="date" name="end_date" rows="1" cols="50"></input>
        <br>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

automation_server/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/style.css">
    <title>All Trips</title>
</head>
<body>
    <h1>Add Trip</h1>
    <form action="{{ url_for('routes.add_trip_with_docx') }}" method="post" enctype="multipart/form-data">
        <label>Upload the trip voucher here to add trip to the system</label>
        <br>
        <input type="file" name="input_file" accept=".docx" required>
        <button type="submit">Upload</button>
    </form>
    <p>Alternative manually enter guest name, pax and start and end date</p>
    <a href="{{ url_for('routes.add_trip_manually') }}" >Add trip manually</a>
    <h1>Ongoing Trips</h1>
    <table border="1" cellpadding="5">
        <thead>
            <tr>
                <th>Guest Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Whatspp group id</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for trip in ongoing_trips %}
            <tr>
                <td><a href="{{ url_for('routes.trip', trip_id=trip.id) }}">{{ trip.guest_name }}</a></td>
                <td>{{ trip.start_date }}</td>
                <td>{{ trip.end_date }}</td>
                <td>
                    {% if trip.whatsapp_group_id %}
                        <p>{{ trip.whatsapp_group_id }}&nbsp;<a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Edit</a></p>
                    {% else %}
                        <a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Provide whatsapp group id</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('routes.delete_trip', trip_id=trip.id) }}">delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h1>Upcoming Trips</h1>
    <table border="1" cellpadding="5">
        <thead>
            <tr>
                <th>Guest Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Whatspp group id</th>
                <th>Ticket</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for trip in upcoming_trips %}
            <tr>
                <td><a href="{{ url_for('routes.trip', trip_id=trip.id) }}">{{ trip.guest_name }}</a></td>
                <td>{{ trip.start_date }}</td>
                <td>{{ trip.end_date }}</td>
                <td>
                    {% if trip.whatsapp_group_id %}
                        <p>{{ trip.whatsapp_group_id }}&nbsp; <a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Edit</a></p>
                    {% else %}
                        <a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Provide whatsapp group id</a>
                    {% endif %}
                </td>
                <td>
                    <form action="{{ url_for('routes.add_ticket', trip_id=trip.id) }}" method="post" enctype="multipart/form-data">
                        <label>Upload tickets folder</label>
                        <input type="file" name="input_file" webkitdirectory mozdirectory  required>
                        <button type="submit">Upload</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="{{ url_for('routes.delete_trip', trip_id=trip.id) }}">
                        <button type="submit" onclick="return confirm('Are you sure?')">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <h1>Messaging</h1>      
    <a href="{{ url_for('routes.send_trip_sheet') }}">Send today's trip sheet to customer</a>
    <p>Information will be obtained from whatsapp chat with transporter</p>

    <!-- <a href="{{ url_for('routes.whatsapp_login') }}">Login to whatsapp</a> -->
    <!-- <br>
    <br>
    <form action="{{ url_for('routes.send_trip_sheet') }}" method="post" enctype="multipart/form-data">
        <label>Upload the transporter trip sheet here to send message to client</label>
        <input type="file" name="input_file" accept=".xlsx *.xls" required>
        <button type="submit">Upload</button>
    </form> -->

</body>
</html>

automation_server/app/templates/past_trips.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/style.css">
    <title>Past Trips</title>
</head>
<body>
    <h1>Past Trips</h1>
    <table border="1" cellpadding="5">
        <thead>
            <tr>
                <th>Guest Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Whatspp group id</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for trip in past_trips %}
            <tr>
                <td><a href="{{ url_for('routes.trip', trip_id=trip.id) }}">{{ trip.guest_name }}</a></td>
                <td>{{ trip.start_date }}</td>
                <td>{{ trip.end_date }}</td>
                <td>
                    {% if trip.whatsapp_group_id %}
                        <p>{{ trip.whatsapp_group_id }}&nbsp;<a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Edit</a></p>
                    {% else %}
                        <a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Provide whatsapp group id</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('routes.delete_trip', trip_id=trip.id) }}">delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </body>
</html>

automation_server/app/templates/request_whatsapp_group_id.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style.css">
    <title>Request for whatsapp id</title>
</head>
<body>
    <h2>{{ trip.guest_name }}</h2>
    <form method="POST">
        <label for="group_id">Please provide whatsapp group id:</label>
        <input type="text" name="group_id" rows="1" cols="50"></textarea>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

automation_server/app/templates/trip.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="../static/style.css">
    <title>Trip</title>
</head>
<body>
    <h1>Trip {{trip.guest_name}} {{trip.start_date}}</h1>
    <p>Guest Name: {{ trip.guest_name }}</p>
    <p>Adults: {{trip.adults}}</p>
    <p>Children: {{trip.children}}</p>
    <p>Tickets</p>
    <ul>
        {% for ticket in trip.attraction_tickets %}
            <li>{{ ticket.date }} - {{ ticket.name }}</li>
        {% endfor %}
    </ul>
    {% if trip.whatsapp_group_id %}
        <p>Whatsapp Group Id: {{trip.whatsapp_group_id}}</p>
        <a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Edit</a>
    {% else %}
        <a href="{{ url_for('routes.whatsapp_group_id', trip_id=trip.id) }}">Provide whatsapp group id</a>
    {% endif %}
</body>
</html>